# #####################################################################
# Automatically generated by qmake (2.01a) ?? 8? 27 19:45:41 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    treeview.h \
    thread.h
SOURCES += main.cpp \
    mainwindow.cpp \
    treeview.cpp \
    thread.cpp
